# Generated by Django 3.2.7 on 2021-09-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigntransfer',
            name='transfer_abroad',
            field=models.BooleanField(),
        ),
    ]
