# Generated by Django 3.2.7 on 2021-09-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_cuentas', '0002_alter_foreigntransfer_transfer_abroad'),
        ('pre_cuentas', '0002_auto_20210918_2136'),
    ]

    operations = [
    ]
